### PR TITLE
fix areEntitiesEqual for entities from JDL without javadoc

### LINKED ISSUE #341: entities in JDL without javadoc are regenerated by import-jdl even if no changes
##### **Overview of the issue**

If entity has no javadoc in JDL and command `jhipster import-jdl` is executed multiple times without changes in JDL then this entity without javadoc is regenerated each time `import-jdl` is executed.

##### **Motivation for or Use Case**

It confuses if `import-jdl` claims that there are changes but actually no changes.  
And this is not optimal to regenerate if no changes.  
And without changes in PR #340 this is causing generating new liquibase changelogs for every unchanged entity which has no javadoc in JDL.

##### **Reproduce the error**

Generate application with `jhipster`  
Compose JDL where exists entities without javadoc  
Import entities from JDL by `jhipster import-jdl`  
Re-execute `jhipster import-jdl` without any change in JDL.

Re-executing `jhipster import-jdl` regenerates entities which has no javadoc in JDL.

##### **Related issues**

jhipster/generator-jhipster#9837  
jhipster/generator-jhipster#9996

##### **Suggest a Fix**

If entity javadoc is missing in JDL then entity configuration parsed from JDL contains key `javadoc` with value `undefined`.  
But in entity configuration read from disk this key `javadoc` is missing.  
By this reason `Object.keys(firstEntity).length !== Object.keys(secondEntity).length` is `true` here: https://github.com/jhipster/jhipster-core/blob/master/lib/utils/object_utils.js#L53 and entity is counted as changed entity.  

Possible fix:

add (removes keys which value is `undefined` before comparison):
```
  Object.keys(firstEntity).forEach(key => firstEntity[key] === undefined && delete firstEntity[key]);
  Object.keys(secondEntity).forEach(key => secondEntity[key] === undefined && delete secondEntity[key]);
```

after this line:
https://github.com/jhipster/jhipster-core/blob/master/lib/utils/object_utils.js#L47

##### **JHipster Version(s)**

```
jhipster@0.0.0 C:\projects\teest\jhipster-error
`-- generator-jhipster@6.1.2  -> C:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": ["et"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * not an ignored comment
 */
entity Location {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
/**
 * Task entity.
 * @author The JHipster team.
 */
entity Task {
  title String,
  description String
}
/**
 * The Employee entity.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate Instant,
  salary Long,
  commissionPct Long
}
entity Region {
  regionName String
}
entity Country {
  countryName String
}
entity Department {
  departmentName String required,
  departmentDescription String
}
entity Job {
  jobTitle String,
  minSalary Long,
  maxSalary Long
}
entity JobHistory {
  startDate Instant,
  endDate Instant,
  language Language
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Location{country} to Country,
  Country{region} to Region,
  Department{location} to Location,
  JobHistory{job} to Job,
  JobHistory{department} to Department,
  JobHistory{employee} to Employee
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to Employee{department},
  Employee{job} to Job{employee}
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

service Location, Task, Region, Country, Department, JobHistory with serviceImpl
paginate Employee, JobHistory with infinite-scroll
paginate Job with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by kaidohallik**
fix #341

Feel free to close this PR if there is better fix for #341

Please make sure the below checklist is followed for Pull Requests.
  - [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-core/pull_requests) are green
  - [x] Tests are added where necessary
  - [ ] Documentation is added/updated where necessary
  - [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: lib/utils/object_utils.js [hunk 1]
```diff
@@ -45,6 +45,8 @@ function merge(object1, object2) {
 }
 
 function areEntitiesEqual(firstEntity, secondEntity) {
+  Object.keys(firstEntity).forEach(key => firstEntity[key] === undefined && delete firstEntity[key]);
```
Comment (MathieuAA) [inline lib/utils/object_utils.js]: For clarity: 

```javascript
Object.keys(firstEntity).forEach(key => {
  if (!firstEntity[key]) {
    delete firstEntity[key];
  }
});
```

Comment (kaidohallik) [reply lib/utils/object_utils.js]: Using `!firstEntity[key]` causes removing also `null`, `''` and `false` values which can lead to unexpected behaviour.  
I'd rather use `firstEntity[key] === undefined` in this suggested construct.

Comment (MathieuAA) [reply lib/utils/object_utils.js]: true that, good point
